steps:
  - id: 'Build fat jar'
    name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
  - id: "Prepare staging directory"
    name: 'ubuntu'
    args: ['mkdir', 'deploy-build']
  - name: 'ubuntu'
    args: ['cp', 'src/main/appengine/app.yaml', 'deploy-build/']
  - name: 'ubuntu'
    args: ['cp', 'target/onboarding-0.0.1-SNAPSHOT.jar', 'deploy-build/']
  - id: "Deploy to AppEngine"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'deploy-build/']
timeout: '1600s'